// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://codtqvdixxrwitnhcqju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvZHRxdmRpeHhyd2l0bmhjcWp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzI4MTksImV4cCI6MjA2OTU0ODgxOX0.9PMNxddYENc6Jcow0PoFN1yPFKVqdcnghGctK-PSOfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});